config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :microposts
  resources :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :title, length: { maximum: 30 }
  # validates :content, length: { maximum: 500 }

  # before_save :assign_user_id, on: :create

  # def self.assign_user_id
  #   self.user_id = current_user.id
  # end
end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:new, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  def show
  end

  def new
    @micropost = Micropost.new
  end

  def edit
  end

  def create
    # mettere un before_action. l'utente deve essere loggato per poter fare il post
    unless logged_in?
      redirect_to login_path, notice: 'Ti prego, fai un check per capire se sei loggato'
    else
      @micropost = Micropost.new(micropost_params)
      @micropost.user_id = current_user.id
      if @micropost.save
        redirect_to @micropost, notice: 'Micropost was successfully created.'
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:title, :content, :user_id, :views)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "basic"

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:notice] = 'Si ma svegliarsi dai. Hai sbagliato la password o email'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: [:show, :edit, :update, :destroy]

  # GET /to_dos
  # GET /to_dos.json
  def index
    @to_dos = ToDo.all
  end

  # GET /to_dos/1
  # GET /to_dos/1.json
  def show
  end

  # GET /to_dos/new
  def new
    @to_do = ToDo.new
  end

  # GET /to_dos/1/edit
  def edit
  end

  # POST /to_dos
  # POST /to_dos.json
  def create
    @to_do = ToDo.new(to_do_params)

    respond_to do |format|
      if @to_do.save
        format.html { redirect_to @to_do, notice: 'To do was successfully created.' }
        format.json { render :show, status: :created, location: @to_do }
      else
        format.html { render :new }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_dos/1
  # PATCH/PUT /to_dos/1.json
  def update
    respond_to do |format|
      if @to_do.update(to_do_params)
        format.html { redirect_to @to_do, notice: 'To do was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do }
      else
        format.html { render :edit }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1
  # DELETE /to_dos/1.json
  def destroy
    @to_do.destroy
    respond_to do |format|
      format.html { redirect_to to_dos_url, notice: 'To do was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do
      @to_do = ToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_do_params
      params.require(:to_do).permit(:name, :completed, :order)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  layout "basic", :only => [:new, :create]

  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1.json
  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
      if @user.save
        log_in @user
        redirect_to @user, notice: 'User was successfully created.'
        @user.send_welcome_email
      else
        render 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_message
    
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AppExperiments
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body
    = render 'shared/navbar'
    .ui.container.margin-30
      = yield
    = render 'shared/footer'

app/views/layouts/basic.html.haml
!!!
%html
  %head
    %title AppExperiments
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'sessions',    media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body
    = yield

app/views/microposts/_form.html.haml
= form_for @micropost, html: {class: "ui large form"} do |f|
  - if @micropost.errors.any?
    .ui.error.message
      %h2
        = pluralize(@micropost.errors.count, "error")
        prohibited this micropost from being saved:
      %ul.list
        - @micropost.errors.full_messages.each do |message|
          %li= message
  .ui.stacked.segment
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :content
      = f.text_area :content
    .field
      = f.submit 'Create post', class: "ui teal button"

app/views/microposts/edit.html.haml
%h2.ui.header Editing micropost
= render 'form'
.back
  = link_to 'Show', @micropost
  |
  \#{link_to 'Back', microposts_path}

app/views/microposts/index.html.haml
.ui.stacked.three.special.cards
  - @microposts.each do |micropost|
    .card
      .blurring.dimmable.image
        .ui.inverted.dimmer
          .content
            .center
              = link_to 'Go', micropost, class: "ui huge teal button"
        = image_tag("https://semantic-ui.com/images/avatar/large/elliot.jpg")
      .content
        %span.header
          = micropost.title
        .meta
          = micropost.user.name
        .description
          %p= truncate(micropost.content, :length => 100)
      .extra.content
        .ui.label
          Created at:
          .detail
            = micropost.created_at.to_formatted_s(:short)

        - if logged_in? && micropost.user_id == current_user.id
          %span.align-right
            = link_to 'Show', micropost, class: "ui grey"
            |
            = link_to 'Edit', edit_micropost_path(micropost), class: "ui grey"
            |
            = link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui danger"

.margin-30
  = link_to 'New Micropost', new_micropost_path

app/views/microposts/new.html.haml
%h1 Crea post
= render 'form'
.margin-30
  = link_to 'Back', microposts_path

app/views/microposts/show.html.haml
-# %p#notice= notice
.ui.text.container
  %h2.ui.center.aligned.icon.header
    %i.circular.users.icon
    = @micropost.user.name
.ui.stacked.teal.segments.posts
  .ui.segment
    %h3= @micropost.title
    %p= simple_format(@micropost.content)
    .ui.divider
    .ui.label
      Pubblicato il:
      .detail
        = @micropost.created_at.to_formatted_s(:short)

= link_to 'Edit', edit_micropost_path(@micropost)
|
\#{link_to 'Back', microposts_path}

app/views/shared/_footer.html.haml
%footer
  .ui.inverted.vertical.footer.segment
    .ui.container
      .ui.stackable.inverted.divided.equal.height.stackable.grid
        .three.wide.column
          %h4.ui.inverted.header About
          .ui.inverted.link.list
            = link_to 'Sitemap', root_path, class: 'item'
            = link_to 'Contact us', root_path, class: 'item'
            = link_to 'Dieu dieu', root_path, class: 'item'
            = link_to 'Saluta Andonio', root_path, class: 'item'
        .three.wide.column
          %h4.ui.inverted.header Bella raga
          .ui.inverted.link.list
            = link_to 'Si vola', root_path, class: 'item'
            = link_to 'Martin', root_path, class: 'item'
            = link_to 'Garrix', root_path, class: 'item'
            = link_to 'Animals', root_path, class: 'item'
        .seven.wide.column
          %h4.ui.inverted.header About
          .ui.inverted.link.list
            %p Dopo vado esco, esco con gli amici, vado all'iper... Questa è la giornata.

app/views/shared/_navbar.html.haml
%header
  .ui.container
    .ui.secondary.pointing.menu
      = image_tag("logo")
      = link_to 'Home', root_path, class: "item"
      = link_to 'About', about_path, class: "item"
      = link_to 'Contact', contact_path, class: "item"
      = link_to 'Help', help_path, class: "item"
      .right.menu
        - if logged_in?
          .ui.simple.dropdown.item
            %span.text
              = @current_user.name
            %i.dropdown.icon
            .menu
              .header Testa di cazzo
              = link_to 'Your posts', microposts_path, class: "item"
              .divider
              = link_to 'Logout', logout_path, method: :delete, class: "item"

        - else
          = link_to 'Login', login_path, class: "ui item"

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/about.html.haml
%h1 about

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/contact.html.haml
%h1 contact

app/views/static_pages/help.html.haml
%h1 Aiuto
%p aiutatemi vi prego

app/views/static_pages/home.html.haml
.ui.vertical.masthead.center.aligned.segment
  .ui.text.container
    %h1.ui.header Welcome to the Kindom of DjTeo
    %p
      This is the DjTeo Website. Here you ken find a lot of musical succes of this immense artist.
    = link_to signup_path do
      .ui.animated.huge.teal.button
        .visible.content Signup now!
        .hidden.content
          %i.right.sign.in.icon
    -# mostrare i post piu popolari. USARE il campo views dei micropost
.ui.vertical.stripe.segment
  .ui.three.column.divided.grid
    .row
      .column
        .thumbnail
          = image_tag("/images/")
          .caption
            - @micropost = Micropost.last
            %h3= @micropost.title
            %p
              = truncate(@micropost.content, :length => 100)
            = link_to "Discover More", @micropost
      .column
        .thumbnail
          = image_tag("/images/")
          .caption
            %h3 Notte a Villafranca Marittima
            %p Verstappen, Ricciardo e Vettel ricordano DjTeo così...
            = link_to "Discover More", @micropost
      .column
        .thumbnail
          = image_tag("/images/")
          .caption
            %h3 Una notte al principato
            %p Verstappen, Ricciardo e Vettel ricordano DjTeo così...
            = link_to "Discover More", @micropost
    .row
      .column
        = link_to "All posts", microposts_path

app/views/to_dos/_form.html.erb
<%= form_for(@to_do) do |f| %>
  <% if @to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
      <% @to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_dos/edit.html.erb
<h1>Editing To Do</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do %> |
<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing To Dos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_dos.each do |to_do| %>
      <tr>
        <td><%= to_do.name %></td>
        <td><%= to_do.completed %></td>
        <td><%= to_do.order %></td>
        <td><%= link_to 'Show', to_do %></td>
        <td><%= link_to 'Edit', edit_to_do_path(to_do) %></td>
        <td><%= link_to 'Destroy', to_do, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To do', new_to_do_path %>

app/views/to_dos/new.html.erb
<h1>New To Do</h1>

<%= render 'form' %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @to_do.name %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @to_do.completed %>
</p>

<p>
  <strong>Order:</strong>
  <%= @to_do.order %>
</p>

<%= link_to 'Edit', edit_to_do_path(@to_do) %> |
<%= link_to 'Back', to_dos_path %>

app/views/users/_form.html.haml
= form_for @user, html: {class: "ui large form"} do |f|
  .ui.stacked.segment
    .field
      .ui.left.icon.input
        %i.user.icon
        = f.text_field :name, placeholder: "Name"
    .field
      .ui.left.icon.input
        %i.at.icon
        = f.text_field :email, placeholder: "Email"
    .field
      .ui.left.icon.input
        %i.lock.icon
        = f.password_field :password, placeholder: "password"
    .field
      .ui.left.icon.input
        %i.lock.icon
        = f.password_field :password_confirmation, placeholder: "password confirmation"
    .field
      = f.submit 'Submit', class: "ui fluid large teal submit button"

- if @user.errors.any?
  .ui.error.message
    %h4
      = pluralize(@user.errors.count, "error")
      prohibited this user from being saved:
    %ul.list
      - @user.errors.full_messages.each do |message|
        %li= message

app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
\#{link_to 'Back', users_path}

app/views/users/index.html.haml
%p#notice= notice
%h1 Listing Users
%table
  %thead
    %tr
      %th Name
      %th Email
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
.ui.middle.aligned.center.aligned.grid.sign-form
  .column.main-container
    %h2.ui.teal.image.header
      .content Sign up
    = render 'form'

    = link_to 'Back', root_path, class: "back"

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
%p
  %strong Email:
  = @user.email
%p
  - @user.microposts.each do |micropost|
    Micropost: #{micropost.content}
= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', users_path}